-- MySQL Script generated by MySQL Workbench
-- Fri Dec 13 22:59:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reservaPrivada
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reservaPrivada
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reservaPrivada` DEFAULT CHARACTER SET utf8 ;
USE `reservaPrivada` ;

-- -----------------------------------------------------
-- Table `reservaPrivada`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservaPrivada`.`categorias` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `reservaPrivada`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservaPrivada`.`proveedores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(90) NOT NULL,
  `direccion` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `reservaPrivada`.`bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservaPrivada`.`bebidas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `categoriaId` INT UNSIGNED NOT NULL,
  `precioUnitario` DECIMAL(8,2) NOT NULL,
  `stock` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `proveedorId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bebidas_categoriaId_idx` (`categoriaId` ASC) ,
  INDEX `fk_bebidas_proveedorId_idx` (`proveedorId` ASC) ,
  CONSTRAINT `fk_bebidas_categoriaId`
    FOREIGN KEY (`categoriaId`)
    REFERENCES `reservaPrivada`.`categorias` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bebidas_proveedorId`
    FOREIGN KEY (`proveedorId`)
    REFERENCES `reservaPrivada`.`proveedores` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservaPrivada`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservaPrivada`.`reservas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(60) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `personas` INT NOT NULL,
  `detalles` VARCHAR(90) NOT NULL,
  `estado` ENUM('Pendiente', 'Confirmada', 'Cancelada') NOT NULL DEFAULT 'Pendiente',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `reservaPrivada`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservaPrivada`.`ventas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `reservaPrivada`.`detallesVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservaPrivada`.`detallesVenta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ventaId` INT UNSIGNED NOT NULL,
  `bebidaId` INT UNSIGNED NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detallesVenta_ventaId_idx` (`ventaId` ASC) ,
  INDEX `fk_detallesVenta_bebidaId_idx` (`bebidaId` ASC) ,
  CONSTRAINT `fk_detallesVenta_ventaId`
    FOREIGN KEY (`ventaId`)
    REFERENCES `reservaPrivada`.`ventas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detallesVenta_bebidaId`
    FOREIGN KEY (`bebidaId`)
    REFERENCES `reservaPrivada`.`bebidas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `reservaPrivada`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservaPrivada`.`mesas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `disponibilidad` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservaPrivada`.`reservasMesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservaPrivada`.`reservasMesa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mesaId` INT UNSIGNED NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `detalles` VARCHAR(255) NOT NULL,
  `estado` ENUM('Pendiente', 'Confirmada', 'Cancelada') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservaMesas_mesaId_idx` (`mesaId` ASC) ,
  CONSTRAINT `fk_reservaMesas_mesaId`
    FOREIGN KEY (`mesaId`)
    REFERENCES `reservaPrivada`.`mesas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
