-- MySQL Script generated by MySQL Workbench
-- Thu Nov 28 10:52:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reservaPrivada
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reservaPrivada
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reservaPrivada` DEFAULT CHARACTER SET utf8 ;
USE `reservaPrivada` ;

-- -----------------------------------------------------
-- Table `reservaPrivada`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservaPrivada`.`categorias` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `reservaPrivada`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservaPrivada`.`proveedores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `reservaPrivada`.`bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservaPrivada`.`bebidas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `categoriaId` INT UNSIGNED NOT NULL,
  `precioUnitario` DECIMAL(8,2) NOT NULL,
  `stock` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `proveedorId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bebidas_categoriaId_idx` (`categoriaId` ASC) ,
  INDEX `fk_bebidas_proveedorId_idx` (`proveedorId` ASC) ,
  CONSTRAINT `fk_bebidas_categoriaId`
    FOREIGN KEY (`categoriaId`)
    REFERENCES `reservaPrivada`.`categorias` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bebidas_proveedorId`
    FOREIGN KEY (`proveedorId`)
    REFERENCES `reservaPrivada`.`proveedores` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservaPrivada`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservaPrivada`.`reservas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(60) NOT NULL,
  `telefono` VARCHAR(30) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `detalles` VARCHAR(150) NOT NULL,
  `estado` ENUM('Pendiente', 'Confirmada', 'Cancelada') NOT NULL DEFAULT 'Pendiente',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
